name: .NET

on:
  push:
    branches: [ master ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: docfx build
    steps:
    - uses: actions/checkout@v1
    - uses: nikeee/docfx-action@v1.0.0
      name: Build Documentation
      with:
        args: docfx.json

        # Publish generated site using GitHub Pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        _token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
